Gecal/urls.py
from django.contrib import admin

from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls import include, url
from django.urls import path, include

from django.conf.urls.static import static

if settings.DEBUG:
    import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gecal/', include('paginasGecal.urls')),
    # path('app_teste/', include('app_teste.urls')),
    # path('denunciar/', include('denunciar.urls')),
    path('', RedirectView.as_view(url='/gecal/', permanent=True)),
    path('__debug__/', include(debug_toolbar.urls)),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paginasGecal/urls.py
from django.urls import path, include
from . import views 
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name = 'paginasGecal'

urlpatterns = [
    path('', views.index, name='index'),
    path('relato_violencia/', views.formulario_denuncia, name='chama_form_denuncia'),
#    path('formulario_denuncia/', views.Denunciar.as_view(), name='formulario_denuncia'),
#     path('qualquerUrl/', views.form2difer, name='qualquerNome'),
    # path('proj3Conteudo/', views.proj3Andamento, name='proj3Conteudo'),
    # path('app_teste/', include('app_teste.urls')),
    # path('denunciar/', include('denunciar.urls')),
    path('admin/', admin.site.urls),
]#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paginasGecal/forms.py
from django import forms
from .models import  Formulario_denuncia
CHOICES = [('vivenciou','Foi vítima'),('presenciou','Foi testemunha')]


class DenunciaForm(forms.ModelForm):

    class Media:
        css = {
            'all': 'estilos.css',
        }

    class Meta:
        model = Formulario_denuncia
        fields = ['nome_denunciante','email_denunciante','telefone_denunciante',
          'tipo_de_experiencia','violencia_fisica','violencia_psicologica','assedio_sexual',
          'estupro', 'assedio_moral','violencia_patrimonial','homofobia','lesbofobia','transfobia',
          'ameaca_verbal','outros','txt_outros','txt_relato']



        labels = {'nome_denunciante': ('Seu nome '), 'violencia_fisica':('Violência Física'),
          'violencia_psicologica':('Violência Psicológica'),'assedio_sexual':('Assédio Sexual'),
          'assedio_moral': ('Assédio Moral'),'violencia_patrimonial':('Violência Patrimonial'),
          'homofobia': ('Homofobia'),'lesbofobia':('Lesbofobia'),'transfobia': ('Transfobia'),
          'ameaca_verbal':('Ameaça Verbal'), 'outros': ('Outros'), 'estupro': ('Estupro'),
          'txt_outros':('Descreva '),'txt_relato':('Descreva o fato')
        }


        help_texts = {'nome_denunciante': ('Nome da pessoa que está fazendo a denúncia')}

        # error_messages = {
        #     'email_denunciante': "This writer's name is too long."
        # }

        #self.fields['name'].error_messages = {'required': 'Please let us know what to call you!'}

        error_messages={'required': 'O formato do email não está valido. ___@___.___'}


        widgets = {
            'nome_denunciante':forms.TextInput(attrs={'class':'form-control',
                  'placeholder':'Insira aqui o nome ','name':'nome_denunciante'}),
            'email_denunciante': forms.TextInput(attrs={'class': 'form-control',
                'name': 'email_denunciante', 'placeholder': 'Aqui o email','type':'email'}),
            'telefone_denunciante': forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Telefone aqui"}),
            'txt_outros':forms.TextInput(attrs={'name':'text_outros','class':'input_inline_block',
                  'disabled':True}),
            'tipo_de_experiencia':forms.RadioSelect(attrs={'class':'radio_bt_django','name':'radio'}),
            'violencia_fisica':forms.CheckboxInput(attrs={'class':'checkbox_checkmark_django'}),
            'violencia_psicologica': forms.CheckboxInput(attrs={'class': 'checkbox_checkmark_django'}),
            'assedio_sexual': forms.CheckboxInput(attrs={'class': 'checkbox_checkmark_django'}),
            'assedio_moral': forms.CheckboxInput(attrs={'class': 'checkbox_checkmark_django'}),
            'estupro': forms.CheckboxInput(attrs={'class': 'checkbox_checkmark_django'}),
            'violencia_patrimonial': forms.CheckboxInput(attrs={'class': 'checkbox_checkmark_django'}),
            'homofobia': forms.CheckboxInput(attrs={'class': 'checkbox_checkmark_django'}),
            'lesbofobia': forms.CheckboxInput(attrs={'class': 'checkbox_checkmark_django'}),
            'transfobia': forms.CheckboxInput(attrs={'class': 'checkbox_checkmark_django'}),
            'ameaca_verbal': forms.CheckboxInput(attrs={'class': 'checkbox_checkmark_django'}),
            'outros': forms.CheckboxInput(attrs={'class': 'checkbox_checkmark_django',
                'onchange':'habilita_desabilita_text_input_django()'}),
        }

paginasGecal/views.py
from datetime import datetime
import pyrebase
import re
from django.shortcuts import render, HttpResponse
from django.views import generic
from .models import historicoGecal, LinhaDePesquisa, Pesquisador, Bolsista, Formulario_denuncia, Fotos_e_Destaques
from django.contrib.auth.forms import UserCreationForm
from .forms import DenunciaForm
import random

# Create your views here.


config = {
    'apiKey': "AIzaSyDbUzZnb0I6tC3n-1ZS5klUZCRmzIi3seQ",
    'authDomain': "dropbox-clone-eb95a.firebaseapp.com",
    'databaseURL': "https://dropbox-clone-eb95a.firebaseio.com",
    'projectId': "dropbox-clone-eb95a",
    'storageBucket': "dropbox-clone-eb95a.appspot.com",
    'messagingSenderId': "71341269427"
}

firebase = pyrebase.initialize_app(config)
authe = firebase.auth()
database = firebase.database()


def index(request):

    if request.method == 'POST':
        gravar_denuncia(request)

    # print('request.GET __ index view')
    # print(request.GET)
    #
    # print('request.Post __ index view')
    # print(request.POST)

    historico = historicoGecal.objects.all().first()
    jumbot = historico.textoJumbotron
    txt_hist = historico.textoHistorico

    pesquisas_andamento = LinhaDePesquisa.objects.all().filter(estagio_do_projeto__exact='a',tipo_de_projeto__exact='p')
    pesquisas_concluidas = LinhaDePesquisa.objects.all().filter(estagio_do_projeto__exact='c',tipo_de_projeto__exact='p')

    projetos_ext_andamento = LinhaDePesquisa.objects.all().filter(tipo_de_projeto__exact='e',estagio_do_projeto__exact='a')
    projetos_ext_concluido = LinhaDePesquisa.objects.all().filter(tipo_de_projeto__exact='e',estagio_do_projeto__exact='c')

    # print("imprimindo projetos de extensão em andamento:")
    # print(projetos_ext_andamento)
    #
    # print("imprimindo projetos de extensão concluídos:")
    # print(projetos_ext_concluido)



    pesquisadores = Pesquisador.objects.all()
    bolsistas = Bolsista.objects.all()

    fotos_e_legendas = Fotos_e_Destaques.objects.all()

    # for  foto in fotos_e_legendas:
    #     print(foto.foto.url)

    contexto  = {'historico':txt_hist,
                 'jumbotron': jumbot,
                 'pesquisas_andamento':pesquisas_andamento,
                 'pesquisas_concluidas':pesquisas_concluidas,
                 'pesquisadores': pesquisadores,
                 'bolsistas':bolsistas,
                 'projeto_de_extensao_andamento':projetos_ext_andamento,
                 'projeto_de_extensao_concluido':projetos_ext_concluido,
                 'fotos_legendas':fotos_e_legendas
    }

    return render(request, 'index.html', context=contexto)

    # return render(request, 'index.html', {'historico':txt_hist, 'jumbotron': jumbot,
    #     'pesquisas_andamento':pesquisas_andamento, 'pesquisas_concluidas':pesquisas_concluidas,
    #     'pesquisadores': pesquisadores, 'bolsistas':bolsistas, 'extensao_andamento':projetos_ext_andamento,
    #     'extensao_concluido':projetos_ext_concluido},)



def formulario_denuncia(request):
    print('entrou no formulário denuncia view')

    if request.method == 'POST':
        form_denuncia = DenunciaForm(request.POST)
        if form_denuncia.is_valid():
            form_denuncia.save()
            form_denuncia = DenunciaForm()
        else:
            print(form_denuncia.errors)
        # print('entrou no formulário denuncia view -- save method')
        # if formulario.is_valid():

        print('entrou no formulário denuncia view -- terminou save ')
    else:
    # print(request.GET)
        form_denuncia = DenunciaForm();

    contexto = {
        'formulario': form_denuncia,
        'registro_denuncia': Formulario_denuncia,
    }

    return render(request, 'paginasGecal/form_denuncia.html', contexto)


ENUM_TODAS_AS_CHAVES = ['radio', 'check_vf', 'check_vps', 'check_as', 'check_es',
'check_am', 'check_vpa', 'check_ho', 'check_le', 'check_tr', 'check_av', 'check_ou',
'text_outros', 'nome_denunciante', 'email_denunciante', 'tel_denunciante', 'txt_relato']

MAP_DICT_TIPO_DE_VIOLENCIA = {
'nome_denunciante':'nome_denunciante',
'email_denunciante':'email_denunciante',
'tel_denunciante':'telefone_denunciante',
'radio':'tipo_de_experiencia',
'check_vf': 'violencia_fisica', 'check_vps': 'violencia_psicologica','check_as': 'assedio_sexual',
'check_es': 'estupro', 'check_am': 'assedio_moral', 'check_vpa': 'violencia_patrimonial', 'check_ho': 'homofobia',
'check_le': 'lesbofobia', 'check_tr':'transfobia', 'check_av':'ameaca_verbal', 'check_ou': 'outros',
'text_outros':'txt_outros',
'txt_relato':'txt_relato'
}

BOOLEAN_DICT_TIPO_DE_VIOLENCIA = {
    'check_vf': True, 'check_vps': True,'check_as': True,
    'check_es': True, 'check_am': True, 'check_vpa': True, 'check_ho': True,
    'check_le': True, 'check_tr': True, 'check_av': True, 'check_ou': True,
}


def gravarNoFirebase(request, denuncia):
    print('entrou no gravar firebase')
    randomId = random.randint(0,999999)
    denuncia['data_relato'] = datetime.today().__str__()
    print(database.child("denuncias").child(randomId).set(denuncia))

def gravar_denuncia(request):

    dados_denuncia = {}
    denuncia = Formulario_denuncia()
    setattr(denuncia, 'tipo_de_experiencia',request.POST['radio'])

    dados_denuncia['tipo_de_experiencia'] = request.POST['radio']

    chaves_post = request.POST.keys()
    # for i in range(len(chaves_post)):
    #     print("imprimindo chaves: " + chaves_post[i])

    for chave in chaves_post:
        # print("imprimindo v2 chaves> " + chave)
        # print("imprimindo valores do request.POST['chave']")
        # print("valor da chave: " + chave + " no request.POST : "+ request.POST[chave])
        if (chave != 'csrfmiddlewaretoken'):
            search = re.search("check", chave)
            # print('search')
            # print(search)
            if (search != None):
                setattr(denuncia, MAP_DICT_TIPO_DE_VIOLENCIA[chave], BOOLEAN_DICT_TIPO_DE_VIOLENCIA[chave])
                dados_denuncia[MAP_DICT_TIPO_DE_VIOLENCIA[chave]] = BOOLEAN_DICT_TIPO_DE_VIOLENCIA[chave]
            elif (chave == 'txt_relato' and request.POST[chave] == 'Insira aqui o relato!'):
                setattr(denuncia, MAP_DICT_TIPO_DE_VIOLENCIA[chave], '')
                dados_denuncia[MAP_DICT_TIPO_DE_VIOLENCIA[chave]] = request.POST[chave]
            else:
                setattr(denuncia, MAP_DICT_TIPO_DE_VIOLENCIA[chave], request.POST[chave])
                dados_denuncia[MAP_DICT_TIPO_DE_VIOLENCIA[chave]] = request.POST[chave]

    print('dados_denuncia >>> ' , dados_denuncia)
    gravarNoFirebase(request,dados_denuncia)
    # print('chaves_post')
    # print(chaves_post)
    # print('chaves_post.length')
    # print(len(chaves_post))
    denuncia.save()


def form2difer(request):
    return render(request, 'formulario_denuncia.html')

def proj3Andamento(request):
    return render(request, 'paginasGecal/proj3Conteudo.html')

paginasGecal/templates/paginasGecal/base.html
<html>

<head>
<title> Denúncia </title>
<meta charset='utf-8' />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% load staticfiles %}
<!-- 	<link rel="stylesheet" href="{% static 'bootstrap_css/bootstrap.min.css' %}" type="text/css" /> -->

<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script
	src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script
	src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

<!--     <link rel="stylesheet" href="{% static 'css/styles.css' %}"/> -->

<style>
.jumbotron {
	background-color: #2E2D88;
	color: white;
}
</style>
</head>

<body class="body" style="background-color: #f6f6f6">

	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target="#myNavBar">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#"> <img
					src="{% static 'imagens/logo_gecal.jpg' %}" class="responsive-img"
					style='max-height: 20px;' alt="face">
				</a>
			</div>
			<div class="collapse navbar-collapse" id="myNavBar">
				<ul class="nav navbar-nav">
					<li class="active"><a href="{% url 'paginasGecal:index' %}">Home</a></li>
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#"> Projetos <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="#"> Projetos de Pesquisa </a></li>
							<li><a href="#"> Projetos de Extensão </a></li>
						</ul></li>
					<li><a href="#">Pesquisadores</a></li>
					<li><a href="#">Bolsistas</a></li>
					<li><a href="#">Galerias</a></li>
					<li><a href="#">Denúncias</a></li>
				</ul>
			</div>
		</div>
	</nav>
	<div class="container">
		<div class="jumbotron">
			<p>
				ManyManyManyManyManyManyManyManyManyManyManyMany
				ManyManyManyManyManyManyManyManyManyManyManyMany
				ManyManyManyManyManyManyManyManyManyManyManyMany
				ManyManyManyManyManyManyManyManyManyManyManyMany
				ManyManyManyManyManyManyManyManyManyManyManyMany
				
				OtherOtherOtherOtherOtherOtherOtherOtherOtherOther
				OtherOtherOtherOtherOtherOtherOtherOtherOtherOther
				OtherOtherOtherOtherOtherOtherOtherOtherOtherOther
				OtherOtherOtherOtherOtherOtherOtherOtherOtherOther</p>


			<!-- BUTTONS -->
			<!-- There are many built in button colors and sizes. If a link is to trigger in page functionality it should use role="button". The button element should be used in most situations -->
			<p>
				<a href="#" class="btn btn-default btn-lg" role="button">More
					info</a>
				<button type="submit" class="btn btn-danger" role="button">Button</button>
				<input type="button" value="Info" class="btn btn-info">
				<button type="submit" class="btn-primary btn-sm">Primary</button>
				<button type="submit" class="btn btn-success btn-xs">Success</button>
				<button type="submit" class="btn btn-warning btn-lg">Warning</button>
				<button type="submit" class="btn btn-link btn-lg">Link</button>
		</div>

		<div class="row">
			<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
				<h4>Coluna 1</h4>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean
				fringilla at libero at finibus. Mauris dui felis, sagittis in
				dapibus eget, porta quis elit. Donec sodales placerat porta. Vivamus
				laoreet magna eget facilisis condimentum. Donec porttitor elit nibh,
				et mollis nunc egestas at. Vestibulum tristique vehicula ligula vel
				mollis. Quisque ante lectus, tincidunt maximus scelerisque in,
				molestie nec eros. Vestibulum finibus, lacus at gravida condimentum,
				tellus mauris imperdiet orci.
			</div>
			<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
				<h4>Column 2</h4>
				Quisque rutrum augue odio, eu placerat diam bibendum id. Donec at
				fringilla leo, non varius magna. Vestibulum finibus, lacus at
				gravida condimentum, tellus mauris imperdiet orci, a pretium justo
				nulla sit amet nunc. Class aptent taciti sociosqu ad litora torquent
				per conubia nostra, per inceptos himenaeos. In fermentum ex ac
				lectus porttitor molestie. Sed cursus velit congue ex venenatis
				accumsan.
			</div>
			<div class="clearfix visible-sm"></div>
			<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
				<h4>Column 3</h4>
				Pellentesque vulputate faucibus leo, non blandit ante faucibus
				maximus. Nunc non neque laoreet, tincidunt nisl et, tristique odio.
				Nullam imperdiet sollicitudin neque malesuada ornare. Curabitur
				ultrices urna id gravida lacinia. Nunc eu neque vitae nisi luctus
				rhoncus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
				Pellentesque habitant morbi tristique senectus et netus et malesuada
				fames ac.
			</div>
			<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
				<h4><a href="#col4Content" data-toggle="collapse"> Column 4 </a> </h4>
				<div id="col4Content" class="collapse in">
				Vestibulum vitae lacus eu metus finibus viverra vel blandit justo.
				Suspendisse ac sapien sapien. In a pellentesque ipsum. Donec quis
				venenatis lectus, at vehicula nulla. Etiam imperdiet tellus sit amet
				lobortis varius. Pellentesque sit amet arcu quis sem pretium luctus.
				Aliquam vitae neque id augue sollicitudin mattis id vitae lorem.
				Quisque a metus fermentum, ultricies diam non, dignissim nibh.
				Aliquam erat
			</div>
		
		</div>
		</div>
	

	<div class="container">
		<div class="row">
		
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#superman">Superman</a></li>
			<li><a data-toggle="tab" href="#batman">Batman</a></li>

			<li class="dropdown"><a class="dropdown-toggle"
				data-toggle="dropdown" href="#">Flash<span class="caret"></span></a>
				<ul class="dropdown-menu">

					<li class="disabled"><a data-toggle="tab" href="#flash">The
							Flash</a></li>
					<li><a data-toggle="tab" href="#kidFlash">Kid Flash</a></li>
				</ul></li>
		</ul>
		<div class="col-md-6">
		<div class="tab-content">
			<div id="superman" class="tab-pane fade in active">
				<p>Superman is a fictional hero
			</div>
			<div id="batman" class="tab-pane fade">
				<p>Batman is a fictional hero
			</div>
			<div id="flash" class="tab-pane fade">
				<p>Flash is a fictional hero
			</div>
			<div id="kidFlash" class="tab-pane fade">
				<p>Kid Flash is a fictional hero
			</div>
		</div>
		</div>
		
		
			<div class="col-md-6">  <!-- col-md-offset-6" -->
			<table class="table table-ordered table-striped table-hover">
			<thead><tr><td colspan="4"> Bolsistas </td></tr></thead>
			<tbody><tr>
				<th class="col-md-2"> </th>
				<th class="text-center"> Funções </th>
				<th class="text-center"> Curso </th>
				<th class="text-center"> Nome </th>
				</tr>
				<tr>
					<td><a href="#"> bolsista 1 </a></td>
					<td>Organizar Papelada burocrática</td>
					<td>Administração</td>
					<td>nome bolsista 1</td>
				</tr>	
				<tr>
					<td><a href="#"> bolsista 2 </a></td>
					<td>Manutenção, comunicação, revisão</td>
					<td>Sistemas de Informação</td>
					<td>nome bolsista 2</td>
				</tr>	
				<tr>
					<td><a href="#"> bolsista 3 </a></td>
					<td>Receber e encaminhar pedidos e solicitações</td>
					<td>Engenharia</td>
					<td>nome bolsista 3</td>
				</tr>	
				
			</tbody>
			
			</table>
		</div>
		</div>
	</div>
		{% block content %} {% endblock %}
	</div>
</body>

<footer>
	<div class="container-fluid" style="margin-left:15px">
		<p><a href="https://www.facebook.com/Gecal-Grupo-de-Pesquisa-em-G%C3%AAnero-Educa%C3%A7%C3%A3o-e-Cidadania-na-Am%C3%A9rica-Latina-1789206161123983/" target="blank">Facebook</a> |
		<a href="http://dgp.cnpq.br/dgp/espelhogrupo/0019510862452049" target="blank">CNPq</a></p>
	</div>
</footer>

</html>

</html>

paginasGecal/templates/paginasGecal/form_denuncia.html
{% extends "modelo_base_uniplac.html" %}

{% block comment %}{% endblock %}

{% block css %}
{% load static %}<link rel="stylesheet"  type="text/css" href="{% static '/css/estilos.css' %}" />
{% endblock %}

{% block style %}
<style>
</style>
{% endblock %}


{% block script %}


<script type="text/javascript" src="{%static '/js/index.js'%}"></script>
<!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.js"></script>-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/0.9.0/jquery.mask.min.js"></script>

<script>$(document).ready(function ($) {
    $.mask.definitions['~'] = '[+-]';
    // $('#data').mask('99/99/9999');
    // $('#cpf').mask('999.999.999-99');
    // $('#rg').mask('99.999.999-9');
    $('#telefone').mask('(99) 9999-9999');
})
</script>
{% endblock %}


{% block content %}
<body>

<hr/>
<div class="row">
	<div class="container-menuLateral col-sm-3">
		<div class="sidenav">
			<a role="button" id="bt_hide_show" onclick="show_hide_texto_historico()" >
			Gecal - Histórico</a>

			<div class="projetos_dropdown">

				<a role="button"> Projetos <span class="caret"></span></a>
				<div class="dropdown-content_projetos">
					<a role="button" class="my_anchor" onclick="mostra_projetos_de_pesquisa()" > Projetos de Pesquisa </a>
					<a role="button" class="my_anchor" onclick="mostra_projetos_de_extensao()" > Projetos de Extensão </a>
				</div>
			</div>

			<a role="button" id="bt_mostra_pesquisadores" onclick="mostra_pesquisadores()"> Pesquisadores </a>
			<a role="button" id="bt_mostra_bolsistas" onclick="mostra_bolsistas()"> Bolsistas </a>
			<a href="#"> Galerias </a>
			<a href="{% url 'paginasGecal:chama_form_denuncia' %}"  id="anchorAdminId"> Relatar Violência </a>
			<a href="{% url 'admin:index' %}"> Acessar Interface Admins </a></a>

			<a role="button" onclick="mostra_formulario()">Observatório de violência</a>
			<a role="button" onclick="mostra_formulario_2()">Observatório de violência - 2 </a>
		</div>
	</div>

	<!-- COMEÇA A DIV QUE MOSTRA O FORMULÁRIO DE DENÚNCIA -->
	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8" style="display:none;"  id="formulario_de_denuncias">
		<h2>Formulário para casos de relato de violência</h2>

		<iframe height="300px" width="100%" src="https://docs.google.com/forms/d/e/1FAIpQLSdWxmbH7rUfnA0Lc19UHllcjZRM1RP1QJs6KX8lRgFITvz2pA/viewform" name="iframe_a"></iframe>
	</div><!-- FECHA A DIV DO FORMULÁRIO DE DENÚNCIA -->

	<!-- COMEÇA A DIV QUE MOSTRA O FORMULÁRIO DE DENÚNCIA2 -->
	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8" style="display:block;"  id="formulario_de_denuncias2">
		<h2 class="jumbotron">FORMULÁRIO PARA RELATO DE CASOS</h2>

		<form action="" method="post">
			{% csrf_token %}


			<!--formulario.tipo_de_experiencia-->
			<!--<span class="checkmark"></span>-->
			<!--<hr/><hr/><hr/>-->

            {{formulario.as_p}}
            {{formulario.errors}}

            <input type="submit" class="btn btn-primary" value="Registrar"/>

		</form>
	</div><!-- FECHA A DIV DO FORMULÁRIO DE DENÚNCIA2 -->



</div>

</body>
<hr/>


{% endblock %}
<br> <br> <br>
<!-- 	</div> -->

<footer>
	<div class="container-fluid" style="margin-left: 15px">
		<p>
			<a
					href="https://www.facebook.com/Gecal-Grupo-de-Pesquisa-em-G%C3%AAnero-Educa%C3%A7%C3%A3o-e-Cidadania-na-Am%C3%A9rica-Latina-1789206161123983/"
					target="blank">Facebook</a> | <a href="http://dgp.cnpq.br/dgp/espelhogrupo/0019510862452049" target="blank">CNPq</a>
		</p>
	</div>
</footer>